name: Gets all changed files, find tabs, generate report

on: [push, pull_request]

jobs:
  find-changed-files:
    runs-on: ubuntu-latest  
    steps:
      - name: Get changed files
        uses: actions/checkout@v2.1.0
        id: files
      - run: |
              ls ./k8s/
              echo "::set-output name=files::$(ls ./k8s/)"
  find-tabs:
    needs: find-changed-files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        changed-files: ${{fromJson(needs.find-changed-files.outputs.files)}}
      fail-fast: false
    steps:
    - name: Test files with kubeval
      uses: instrumenta/kubeval-action@master
      with: 
       files: ${{matrix.changed-files}}
