name: Kube runner check

on:
  push:
    branches: [ master ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: self-hosted
    steps:
      - run: | 
              echo "HELLO FROM RUNNER"
