name: Gets all changed files, find tabs, generate report

on:
  push:
    branches:
    - master

jobs:
  find-tabs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - name: Get changed files
        uses: jitterbit/get-changed-files@v1
        id: files
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}  
      - run: | 
              echo "List of changed files got succesfully"
              ls -la
              echo "${{ steps.files.outputs.all }}"
      - name: Find tabs
        run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
              cat ${changed_file} | grep "   " > ${changed_file}.log 2>&1
          done
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          path: ${{ steps.files.outputs.all }}.log
