name: Gets all changed files, find tabs, generate report

on:
  push:
    branches:
    - master

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Get changed files
        uses: jitterbit/get-changed-files@v1
        id: files
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}  
      - run: | 
              echo "List of changed files got succesfully" 
              echo "${{ steps.files.outputs.all }}"
      - name: Find tabs
        run: |
          cat ${{ steps.files.outputs.all }} | grep "	" > ${{ steps.files.outputs.all }}.log 2>&1
          ls -la
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          path: ${{ steps.files.outputs.all }}.log
