name: Gets all changed files, find tabs, generate report

on:
  push:
    branches:
    - master

jobs:
  find-changed-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - name: Get changed files
        uses: jitterbit/get-changed-files@v1
        id: files
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}  
      - run: | 
              echo "List of changed files got succesfully"
              echo "${{ steps.files.outputs.all }}"
  find-tabs:
    runs-on: ubuntu-latest
       strategy:
        matrix:
          changed-files: ${{ steps.files.outputs.all }}
      - name: Find tabs
        run: |
              cat ${{changed-files}} | grep "   " > ${{changed-files}}.log 2>&1
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          path: ${{ changed-files }}.log
